<define-tag pagetitle>DSA-1619-1 python-dns</define-tag>
<define-tag report_date>2008-7-27</define-tag>
<define-tag secrefs>CVE-2008-1447 CVE-2008-4099 Bug#490217</define-tag>
<define-tag packages>python-dns</define-tag>
<define-tag isvulnerable>yes</define-tag>
<define-tag fixed>yes</define-tag>

#use wml::debian::security

<h3>Debian GNU/Linux 4.0 (etch)</h3>

<dl>

<dt><source />

  <dd><fileurl http://security.debian.org/pool/updates/main/p/python-dns/python-dns_2.3.0.orig.tar.gz />
  <dd><fileurl http://security.debian.org/pool/updates/main/p/python-dns/python-dns_2.3.0-5.2+etch1.diff.gz />
  <dd><fileurl http://security.debian.org/pool/updates/main/p/python-dns/python-dns_2.3.0-5.2+etch1.dsc />

<dt><arch-indep />

  <dd><fileurl http://security.debian.org/pool/updates/main/p/python-dns/python-dns_2.3.0-5.2+etch1_all.deb />

</dl>

<p><md5sums http://lists.debian.org/debian-security-announce/2008/msg00204.html /></p>
