#use wml::debian::translation-check translation="1.1" maintainer="Nicolas Bertolissio"

<define-tag description>Usurpation de réponse DNS</define-tag>
<define-tag moreinfo>

<p>
Plusieurs faiblesses ont été identifiées dans PyDNS, un client DNS implanté en
langage Python. Dan Kaminsky a identifié un vecteur concret d'usurpation de
réponse DNS et d'empoisonnement du cache exploitant l'entropie limitée dans un
identifiant de transaction DNS et dans le manque de sélection aléatoire de port
UDP source dans plusieurs implantations de DNS. Scott Kitterman a indiqué que
python-dns était vulnérable à cette prévisibilité, car il ne rend aléatoire ni
ses identifiants de transactions ni ses ports sources. Ce manque d'entropie
laisse les applications réalisant des requêtes DNS <i>via</i> python-dns
fortement vulnérables à la contrefaçon des réponses.
</p>

<p>
Le projet des expositions et vulnérabilités communes (CVE) identifie cette
faiblesse sous la référence
<a href="http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-1447">CVE-2008-1447</a>.
</p>

<p>
Pour la distribution stable (<em>Etch</em>), ce problème a été corrigé dans la
version&nbsp;2.3.0-5.2+etch1.
</p>

<p>
Nous vous recommandons de mettre à jour vos paquets python-dns.
</p>

</define-tag>

# ne pas modifier la ligne suivante
#include "$(ENGLISHDIR)/security/2008/dsa-1619.data"
