#use wml::debian::translation-check translation="1.1" maintainer="Lev Lamberov"
<define-tag description>отказ в обслуживании</define-tag>
<define-tag moreinfo>
<p>Было обнаружено, что python-django, инфраструктура высокого уровня для веб-разработки на
Python, имеет уязвимость, состоящую в отказе в обслуживании, при
использовании длинных паролей.</p>

<p>Неавторизованный удалённый атакующий может вызвать отказ в обслуживании,
вводя произвольные длинные пароли, что приводит к тому, что сервер затрачивает ресурсы на
вычисление соответствующих хэшей для проверки
пароля.</p>

<p>В предыдущем стабильном выпуске (squeeze) эта проблема была исправлена в
версии 1.2.3-3+squeeze8.</p>

<p>В стабильном выпуске (wheezy) эта проблема была исправлена в
версии 1.4.5-1+deb7u4.</p>

<p>В нестабильном выпуске (sid) эта проблема была исправлена в
версии 1.5.4-1.</p>

<p>Мы рекомендуем вам обноваить ваши пакеты python-django.</p>
</define-tag>

# do not modify the following line
#include "$(ENGLISHDIR)/security/2013/dsa-2758.data"
# $Id$

